package r.analysis;

/** If an RNode field is marked with this annotation, it will not be visited during the linearVisit process. This only
 * applies to RNodes with autogenerated linearVisit methods and RNode fields as only those are visited.
 */
public @interface DoNotVisit {
}
