package r.analysis.codegen.annotations;

import java.lang.annotation.*;

/** If a RNode field is marked with the DoNotVisit interface, it will not be visited by the autogenerated code created
 * by the FastrLoader.
 *
 * This annotation is to mark executable tree components that are not really executable (e.g. backup nodes, etc.)
 */
@Target(ElementType.FIELD)
public @interface DoNotVisit {
}
