/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class r_ext_MKL */

#ifndef _Included_r_ext_MKL
#define _Included_r_ext_MKL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     r_ext_MKL
 * Method:    vdAdd
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdAdd
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdSub
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdSub
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdMul
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdMul
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdDiv
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdDiv
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdPow
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdPow
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzAdd
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzAdd
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzSub
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzSub
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzMul
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzMul
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzDiv
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzDiv
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzPow
 * Signature: (I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzPow
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdPowx
 * Signature: (I[DD[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdPowx
  (JNIEnv *, jclass, jint, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdSqr
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdSqr
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdAbs
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdAbs
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vdSqrt
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vdSqrt
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     r_ext_MKL
 * Method:    vzAbs
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_r_ext_MKL_vzAbs
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
